---
title: "Reading dvw files"
---

## DVW files

The data project scouting software, data volley 4, files are the focus on this package. If your interested in some example files, you can find them [here](https://mevza.volleynet.at/Download/59).

## Reading a single dvw

The provided example file is used. You would typically fill in the `None` with the actual path of your dvw files.

```{python}
import pandas as pd
from datavolley import read_dv
pd.set_option('display.max_columns', None) # Used so we can see the entire dataframe as it prints
pd.set_option('display.width', 300)
dv_instance = read_dv.DataVolley(None) # Replace `None` with path of your dvw file 
df = dv_instance.get_plays()
print(df[(df['skill'].notna()) & (df['skill'] != "Point")].head(10))
```

## Reading multiple dvw files

There are different methods when reading more than one dvw file. If you have more than 200 files you may consider using [`threading`](https://www.pythontutorial.net/python-concurrency/python-threading/).

Here is one method to reading multiple files from a folder.

```{python}
import pandas as pd
from datavolley import read_dv
import os

# Assign path
dvw_path_folder = os.path.expanduser("~\\desktop\\dvws")
file_extension = ".dvw"

# Get a list of all files with the specified extension in the directory
file_list = [f for f in os.listdir(dvw_path_folder) if f.endswith(file_extension)]

# Initialize an empty DataFrame to store combined data
combined_df = pd.DataFrame()

def process_file(path):
    dv_instance = read_dv.DataVolley(os.path.join(dvw_path_folder, path))
    df = dv_instance.get_plays()
    return df

# Loop through each file path
for file_name in file_list:
    combined_df = pd.concat([combined_df, process_file(file_name)], ignore_index=True)

print("DVW files read: " + str(len(combined_df['match_id'].unique())))

print(combined_df[(combined_df['skill'].notna()) & (combined_df['skill'] != "Point")].head(10))
```

## Reading multiple dvw files from different folders

In the event you have dvw files inside multiple folders, you may consider the following method to parse those:

```{python}
import pandas as pd
from datavolley import read_dv
import os

# Assign path
dvw_path_folder = os.path.expanduser("~\\desktop\\dvws")
file_extension = ".dvw"

# Initialize an empty DataFrame to store combined data
combined_df = pd.DataFrame()

def process_file(path):
    dv_instance = read_dv.DataVolley(os.path.join(dvw_path_folder, path))
    df = dv_instance.get_plays()
    return df

# Loop through each file path in the directory and its subdirectories
for root, dirs, files in os.walk(dvw_path_folder):
    for file_name in files:
        if file_name.endswith(file_extension):
            file_path = os.path.join(root, file_name)
            combined_df = pd.concat([combined_df, process_file(file_path)], ignore_index=True)

print("DVW files read: " + str(len(combined_df['match_id'].unique())))

print(combined_df[(combined_df['skill'].notna()) & (combined_df['skill'] != "Point")].head(10))
```

## Saving the dataframe as a csv

If you'd like to save your data into a csv.

```{python}
#combined_df.to_csv('combined_data.csv') # Where your current directory lives
```

However, this method may present issues when it comes to encoding. You may want to choose some alternate methods when encoding becomes an issue. Saving to excel is one option.

```{python}
# You may need to run pip install openpyxl before saving to excel
#combined_df.to_excel('combined_data.xlsx')
```